### ISSUE TITLE
The bot should be able to do simple math

### ISSUE THREAD

**Issue by swt2public** [derari/pythontest#5]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

>Got string indices must be integers, not str

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

>Got string indices must be integers, not str

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

>Got string indices must be integers, not str

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

>Got Exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 43, in test_math1
    response = 1 / 0 # reply("1+1")
ZeroDivisionError: integer division or modulo by zero
```

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 43, in test_math1
    response = 1 / 0 # reply("1+1")
ZeroDivisionError: integer division or modulo by zero
```

**Comment by swt2public** [comment]
Given a tweet "1+1",  
		Then the bot's answer should contain "2".
		
		* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
		* To parse an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 51, in test_math1
    response = reply_to("1+1")
NameError: global name 'reply_to' is not defined
```

**Comment by swt2public** [comment]
Given a tweet "1+1",  
		Then the bot's answer should contain "2".
		
		* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
		* To convert a  string to an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 51, in test_math1
    response = reply_to("1+1")
NameError: global name 'reply_to' is not defined
```

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
* To convert a  string to an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 52, in test_math1
    response = reply_to("1+1")
NameError: global name 'reply_to' is not defined
```

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
* To convert a  string to an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 52, in test_math1
    response = self.reply_to("1+1")
TypeError: reply_to() takes exactly 1 argument (2 given)
```

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
* To convert a  string to an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Failed, got exception:
```
Traceback (most recent call last):
  File "travis_test.py", line 53, in test_math1
    self.expect_contains("response", response, "2")
  File "travis_test.py", line 33, in expect_contains
    if substr not in string:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
* To convert a  string to an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Expected response containing "2",  
but got `None`

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
* To convert a  string to an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Expected response containing "2",  
but got `None`

**Comment by swt2public** [comment]
Given a tweet "1+1",  
Then the bot's answer should contain "2".

* To split the term into operands, you can use [`string.split('+')`](https://docs.python.org/2/library/stdtypes.html#str.split).
* To convert a  string to an integer, you can use [`int(string)`](https://docs.python.org/2/library/functions.html#int).
		

>Expected response containing "2",  
but got `None`
